### PR TITLE
Updated homepage logo

### PR DESCRIPTION
**Pull request by PixelJanitor**
image

### CODE REVIEW

**Comment by PixelJanitor** [comment]
image

Most recent version with better proportioned logo

**Comment by fotinakis** [comment]
screen shot 2018-01-29 at 2 17 38 pm

@PixelJanitor the spacing around the My Dashboard button when logged-in version looks pretty different from the logged-out Sign In Button, which looks right.

**Comment by PixelJanitor** [comment]
I see something different locally...

screen shot 2018-01-29 at 5 31 28 pm

**Comment by fotinakis** [comment]
@PixelJanitor going to merge and ship this! 🎉

**Pull request merged**
