### PR TITLE
Update three links to docs (Tutorials & GitHub integration)

### PR DESCRIPTION
**Pull request by Robdel12**
## Description

This PR updates / fixes two different links to documentation pages. The first is in the main nav that should link to different tutorials that are available. Currently it's using an ember `link-to` & relies on the redirect from the deprecated `docs` route, which is broken in this instance. Instead of updating the redirect, we can skip it entirely and link directly to the spot we need. 

The second is updating a link to GitHub integration. I couldn't find anything in the docs specific to "Pull Request integration" for GitHub so I linked to the GitHub integration docs instead. Let me know if the messaging for this alert should change. 

The third link is a link to pull request integration docs from the organization settings page. I linked to the first integration doc since there's no index page for integrations (looks like there was before, which is why this is broken?)

## Pictures 

I normally include GIFs in my PRs but I couldn't get the non-marketing part of the site to work in mirage mode. There's a factory error that I didn't want to jump into debugging for this PR :p

## Reviewing this PR

- [ ] Make sure the links are correct _for sure_

### CODE REVIEW

**Comment by maprules1000** [comment]
Hey Robert! Thanks for the PR, and sorry you ran into those broken links. We actually just merged a PR to remove the deprecated `buildTarget` so it would be great if you could rebase and we can take another look at it.

**Comment by maprules1000** [comment]
@Robdel12 if you rebase you'll also get some fixes that should reduce those percy changes

**Comment by Robdel12** [comment]
@maprules1000 awesome, let me rebase this really quick for ya!

**Comment by Robdel12** [comment]
No problem! Thanks for getting this through 😃 I'm going to assume those diffs came from icons not rendering properly (`percy-agent`)?

**Comment by maprules1000** [comment]
No problem! Thanks again for catching these links!

Yeah, we're testing `percy-agent` before we start rolling it out to our other clients and there are some kinks still to iron out. 

We're also testing out public projects so it's really awesome that you can see those diffs when you contribute!

**Pull request merged**
