### PR TITLE
Multiple accounts UI

### PR DESCRIPTION
**Pull request by cadeParade**

### CODE REVIEW

**Comment by cadeParade** [comment]
@PixelJanitor next week can you take a look at this? There is an alignment problem in the updated sidebars

settings_-_percy___continuous_visual_reviews_for_web_apps

The rows have the `Button` class which has `text-align` center. They used to also have an overriding `Panel.Panel-nav` class which made `text-align: left`, but no more.

**Comment by PixelJanitor** [comment]
Ew! Yea I’ll take care of it!

**Comment by PixelJanitor** [comment]
The sidebar list component classes have been updated for the project settings sidebar:

screen shot 2018-01-08 at 9 33 33 am

**Comment by djones** [comment]
Ship it! 🚀 🚀 🚀 🚀 🚀

**Pull request merged**
