### PR TITLE
Refactor panels into components

### PR DESCRIPTION
**Pull request by cadeParade**
Take these things:
percy___continuous_visual_reviews_for_web_apps
percy___continuous_visual_reviews_for_web_apps

And make them a single component.

### CODE REVIEW

**Comment by faun** [comment]
Q: why are your diffs[erent]?

**Comment by cadeParade** [comment]
@faun they are only _slightly_ different which I am gong to call close enough to be the "same" in this case

**Comment by cadeParade** [comment]
@PixelJanitor Just an FYI, in case you need to use this style of panel again, it is now in a component! Also in case we want to change how these panels look, it is in a component!

**Comment by PixelJanitor** [comment]
🎉

**Pull request merged**
